lightitparticipants/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('participantsapp.urls', namespace='participantsapp')),
]

admin.autodiscover()

participantsapp/urls.py
from django.conf.urls import url
from participantsapp import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^quiz/$', views.AddProjectFormView.as_view(), name='quiz'),
    url(r'^projects/$', views.ProjectsView.as_view(), name='projects'),
    url(r'^project-details/(?P<pk>[0-9]+)/$',
        views.ProjectDetailView.as_view(),
        name='project_details'),
    url(r'file/(?P<pk>\d+)/$', views.get_file, name='get_project_file')
]

participantsapp/models/project.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings


class Project(models.Model):
    name = models.CharField(max_length=100, verbose_name='Project name')
    live = models.BooleanField(
        default=False, verbose_name='Is this project live')
    url = models.CharField(
        blank=True, max_length=255, verbose_name='Project URL')
    url_does_not_exist = models.BooleanField(
        default=False, verbose_name='There is no URL for this project')
    reason = models.CharField(
        blank=True, max_length=255,
        verbose_name='Why there is no URL for this project?')
    manager = models.ForeignKey(
        'Manager', verbose_name='Project manager instance')
    date_start = models.DateTimeField(verbose_name='Start date')
    date_end = models.DateTimeField(
        null=True, blank=True, verbose_name='End date')
    working_now = models.BooleanField(
        default=False, verbose_name='Still working on this project')
    developer = models.ForeignKey(settings.AUTH_USER_MODEL)
    description = models.TextField(verbose_name='Project description')
    skill = models.ManyToManyField('Skill', verbose_name='Skill list')
    nda = models.BooleanField(
        default=False, verbose_name='Non-disclosure agreement')
    files = models.ManyToManyField(
        'ProjectAttachFile', blank=True, verbose_name='Files list')

    def __str__(self):
        return '%s' % self.name

    def __unicode__(self):
        return '%s' % self.name

participantsapp/forms/project.py
from django import forms
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

from multiupload.fields import MultiFileField

from participantsapp.models import Project, ProjectAttachFile
from lightitparticipants.widgets import HorizRadioSelect


class ProjectForm(forms.ModelForm):
    live = forms.ChoiceField(
        widget=HorizRadioSelect,
        choices=[(True, 'Yes'), (False, 'No')],
        initial=True)
    files = MultiFileField(
        max_num=10, max_file_size=1024*1024*5)

    use_required_attribute = False

    class Meta:
        model = Project

        fields = (
            'name', 'url', 'url_does_not_exist', 'reason', 'manager',
            'date_start', 'date_end', 'working_now', 'live',
            'description', 'skill', 'developer', 'files')

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        self.fields['files'].required = False

        for field in self.fields.itervalues():
            field.widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

        self.fields['url'].widget.attrs.update({
            'value': 'http://'
        })

        self.fields['live'].widget.attrs.update({
            'class': '',
        })

    def clean(self):
        super(ProjectForm, self).clean()

        cleaned_data = self.cleaned_data

        if cleaned_data['url_does_not_exist'] and not cleaned_data['reason']:
            self._errors['reason'] = self.error_class(
                ['This field is required.'])

        if not cleaned_data['url_does_not_exist'] and not cleaned_data['url']:
            self._errors['url'] = self.error_class(
                ['This field is required.'])

        if not cleaned_data['url_does_not_exist'] and cleaned_data['url']:
            validate = URLValidator()
            url = self.cleaned_data.get('url')

            try:
                validate(url)
            except ValidationError:
                self._errors['url'] = self.error_class(
                    ['URL is not valid.'])

        return cleaned_data

    def save(self):
        projectform = super(ProjectForm, self).save(commit=False)
        projectform.save()

        for skill in self.cleaned_data['skill']:
            skill.save()
            projectform.skill.add(skill)

        for file in self.cleaned_data['files']:
            attachment = ProjectAttachFile(file=file)
            attachment.save()
            projectform.files.add(attachment)

        projectform.save()

        return projectform

participantsapp/forms/register.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="First name")
    last_name = forms.CharField(label="Last name")

    use_required_attribute = False

    class Meta:
        model = User
        fields = (
            "first_name", "last_name", "email")

    def __init__(self, request=None, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for field in self.fields.itervalues():
            field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': field.label,
                'autocomplete': 'off'
            })

    def clean_email(self):
        data = self.cleaned_data['email']
        try:
            User.objects.get(email__iexact=data)
        except User.DoesNotExist:
            return data

        raise forms.ValidationError("This email has already existed.")

    def save(self):
        user = super(RegisterForm, self).save(commit=False)
        user.username = '%s %s (%s)' % (
            user.first_name, user.last_name, user.email)
        user.save()

participantsapp/views/login.py
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.contrib.auth import login

from participantsapp.forms import EmailAuthenticationForm


class LoginFormView(FormView):
    form_class = EmailAuthenticationForm

    template_name = "login.html"

    success_url = "/quiz"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/quiz')
        else:
            return super(LoginFormView, self).dispatch(
                request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        return super(LoginFormView, self).form_valid(form)

participantsapp/views/projectdetails.py
# coding: utf-8
import mimetypes

from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from participantsapp.models import Project, ProjectAttachFile


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project

    template_name = 'project-details.html'

    context_object_name = 'proj_details'

    def get_queryset(self):
        return Project.objects.all()


def get_file(request, pk):
    f = get_object_or_404(ProjectAttachFile, pk=pk)

    fsock = open(f.file.name, "rb")

    mimetypes.init()
    fname = f.file.name.split('/')[-1]
    mime_type_guess = mimetypes.guess_type(fname)

    response = HttpResponse(fsock, content_type=mime_type_guess[0])
    response['Content-Disposition'] = \
        'attachment; filename="{}"'.format(fname)
    response['Content-Length'] = f.file.size

    return response

participantsapp/views/projects.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.db.models import Value
from django.db.models.functions import Concat

from participantsapp.models import Project


class ProjectsView(LoginRequiredMixin, ListView):
    model = Project

    template_name = 'projects.html'

    context_object_name = "projects"

    paginate_by = 10

    def get_queryset(self):
        list_filters = []
        key_filters = {}

        if not self.request.user.is_staff:
            key_filters['developer_id'] = self.request.user.id

        if self.request.GET.get('search'):
            search = self.request.GET.get('search').strip()
            list_filters.append(
                models.Q(name__icontains=search) |
                models.Q(manager_name__icontains=search) |
                models.Q(url__icontains=search) |
                models.Q(full_name__icontains=search) |
                models.Q(skill__name__icontains=search)
            )

        order_by = self.request.GET.get('orderby') or 'name'
        full_name = Concat(
            'developer__last_name', Value(' '), 'developer__first_name')
        manager_name = Concat(
            'manager__last_name', Value(' '), 'manager__first_name')

        return Project.objects.annotate(
            full_name=full_name, manager_name=manager_name).distinct().filter(
                *list_filters, **key_filters).order_by(order_by)

participantsapp/views/register.py
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect

from participantsapp.forms import RegisterForm


class RegisterFormView(FormView):
    form_class = RegisterForm

    success_url = "/login"

    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/quiz')
        else:
            return super(RegisterFormView, self).dispatch(
                request, *args, **kwargs)

templates/admin_login.html
{% extends "admin/login.html" %}
{% load i18n staticfiles %}
{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/admin-template.css' %}" type="text/css" />
{% endblock %}
{% block content %}
  {% if form.errors and not form.non_field_errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
  {% endif %}
  {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
      <p class="errornote">
        {{ error }}
      </p>
    {% endfor %}
  {% endif %}
  <div id="content-main">
    {% if user.is_authenticated %}
      <p class="errornote">
      {% blocktrans trimmed %}
          You are authenticated as {{ username }}, but are not authorized to
          access this page. Would you like to login to a different account?
      {% endblocktrans %}
      </p>
    {% endif %}
    <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
      <div class="form-row">
        {{ form.email.errors }}
        {{ form.email.label_tag }} {{ form.email }}
      </div>
      <div class="form-row">
        {{ form.password.errors }}
        {{ form.password.label_tag }} {{ form.password }}
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
      {% url 'admin_password_reset' as password_reset_url %}
      {% if password_reset_url %}
      <div class="password-reset-link">
        <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
      </div>
      {% endif %}
      <div class="submit-row">
        <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
      </div>
    </form>
  </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
  {% block head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flat-ui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" />
    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/flat-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/default.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>    
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>    
    <title>{% block title %}{% endblock %} - LightIT Participations</title>
  {% endblock %}
  </head>
  <body>
    <div class="block-header">
      <a href="{% url 'participantsapp:projects' %}"><img class="project-icon" src="{% static 'img/Projects-icon-480x200.png' %}" /></a>
      {% if request.user.username %}
      <div class="logout">
          {{ request.user.first_name }} {{ request.user.last_name }} <a class="btn btn-info btn-lg" href="{% url 'participantsapp:logout' %}"> <span class="glyphicon glyphicon-log-out"></span> Log out </a>
      </div>
      {% endif %}
    </div>    
    <div id="content">{% block content %}{% endblock %}</div>
  </body>
</html>

templates/login.html
{% extends "base.html" %}
{% load base_extra %}
{% block title %}Login page{% endblock %}
{% block content %}
<div class="container mt-300">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong> Sign in </strong>
        </div>
        <div class="panel-body">
          <form role="form" action="{% url 'participantsapp:login' %}" method="POST">
            {% csrf_token %}
            {% if form.non_field_errors or form.this_is_the_login_form.errors %}
              {% for error in form.non_field_errors %}
              <p class="form-field-error form-error">{{ error }}</p>
              {% endfor %}
            {% endif %}
            <formset>
              <div class="row">
                <div class="col-sm-12 col-md-10  col-md-offset-1">
                  {% for field in form %}
                    <div class="form-group">
                      <div class="input-group">
                        <span class="input-group-addon">
                            <i class="glyphicon glyphicon-{{ field.name|glyphicon_tags }}"></i>
                        </span>
                        {{ field }}
                      </div>
                      {% if field.errors %}
                        {{ field.errors }}
                      {% endif %}
                    </div>
                  {% endfor %}
                  <div class="form-group">
                    <input type="submit" class="btn btn-lg btn-info btn-block btn-signin" value="Login">
                  </div>
                  <a class="btn btn-lg btn-info btn-block btn-signup" href="{% url 'participantsapp:register' %}"> Sign Up </a>
                </div>
              </div>
            </formset>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright"> LightIT © 2016 </div>
</div>
{% endblock %}

templates/project-details.html
{% extends "base.html" %}
{% load base_extra %}
{% block title %}Project details{% endblock %}
{% block content %}
<div class="container mt-100">
  <p class="h1 text-center">{{ proj_details.name}}</p>
  <div class="row is-table-row">
    <div class="col-md-4 col-sm-4 well">
      <i class="glyphicon glyphicon-link"></i>{% if proj_details.url %}<a target="_blank" href="{{ proj_details.url }}" class="blue-link">{{ proj_details.url }}</a>{% endif %}{% if proj_details.reason %}{{ proj_details.reason }}{% endif %}
    </div>
    <div class="col-md-4 col-sm-4 well">
      <span class="glyphicon glyphicon-user"></span><a target="_blank" class="blue-link" href="{% url 'participantsapp:projects' %}?search={{ proj_details.developer.last_name }}+{{ proj_details.developer.first_name }}">{{ proj_details.developer.last_name }} {{ proj_details.developer.first_name }}</a> / <a target="_blank" class="blue-link" href="{% url 'participantsapp:projects' %}?search={{ proj_details.manager }}">{{ proj_details.manager }}</a>
    </div>
    <div class="col-md-4 col-sm-4 well">
      <span class="glyphicon glyphicon-calendar"></span>{{ proj_details.date_start|date:"d M Y" }} - {{ proj_details.date_end|date:"d M Y" }}
    </div>
  </div>
  <div class="row is-table-row">
    <div class="col-md-9 well">
      <h6>Description:</h6>
      {% if proj_details.description %}
        {{ proj_details.description }}
      {% else %}
        Not exist
      {% endif %}
      <br/>
      <h6>Attached files:</h6>
      {% for f in proj_details.files.all %}        
        <a class="blue-link" href="{% url 'participantsapp:get_project_file' f.id %}">{{ f.file.name|get_last_url_part }}</a><br/>
      {% endfor %}
    </div>
    <div class="col-md-3 well">
      <h6>Skills:</h6>
      {% if proj_details.skill.all %}
        {% for skill in proj_details.skill.all %}
          <a target="_blank" class="blue-link" href="{% url 'participantsapp:projects' %}?search={{ skill.name|urlencode }}">{{ skill.name }}{% if not forloop.last %}, {% endif %}</a>
        {% endfor %}
      {% else %}
        No data
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

templates/projects.html
{% extends "base.html" %}
{% load staticfiles base_extra %}
{% block title %}Projects{% endblock %}
{% block head %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/highlight.jquery.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container mt-100">
  <div class="row">
    <div>
      <h3 class="h3-proj">Projects</h3>
      <a class="btn btn-info addproject" href="{% url 'participantsapp:quiz' %}">ADD ANOTHER PROJECT</a>
      {% if request.GET.search %}<a class="btn btn-info search_buttons" href="{% url 'participantsapp:projects' %}">CANCEL</a>{% endif %}
      <form class="search-proj-form" action="{% url 'participantsapp:projects' %}" method="GET">
        <input id="id_orderby" name="orderby" type="hidden" value="{% if request.GET.orderby %}{{ request.GET.orderby }}{% endif %}" />
        <input type="submit" class="btn btn-lg btn-info btn-block search_buttons el-width-110" value="SEARCH" />
        <input id="id_search" class="form-control search_buttons el-width-200" autocomplete="off" name="search" value="{% if request.GET.search %}{{ request.GET.search }}{% endif %}" type="text" />
      </form>
    </div>
    {% if projects %}
      <table id="allProjectsTable" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th><a href="{% url 'participantsapp:projects' %}?{% add_url_params request.GET 'name' %}">Project<span class="glyphicon {% is_order_by request.GET 'name' %}"></span></a></th>
            <th>Live</th>
            <th>URL</th>
            <th>Skills</th>
            <th><a href="{% url 'participantsapp:projects' %}?{% add_url_params request.GET 'manager__last_name' %}">Manager<span class="glyphicon {% is_order_by request.GET 'manager__last_name' %}"></span></a></th>
            <th><a href="{% url 'participantsapp:projects' %}?{% add_url_params request.GET 'date_start' %}">Start date<span class="glyphicon {% is_order_by request.GET 'date_start' %}"></span></a></th>
            <th><a href="{% url 'participantsapp:projects' %}?{% add_url_params request.GET 'date_end' %}">End date<span class="glyphicon {% is_order_by request.GET 'date_end' %}"></span></a></th>
            <th><a href="{% url 'participantsapp:projects' %}?{% add_url_params request.GET 'developer_id' %}">Developer<span class="glyphicon {% is_order_by request.GET 'developer_id' %}"></span></a></th>
            {% if request.user.is_staff %}<th>NDA</th>{% endif %}
          </tr>
        </thead>
        {% for project in projects %}
          <tr>
            <td><a href="{% url 'participantsapp:project_details' project.id %}">{{ project.name }}</td>
            <td class="center">{% if project.live %}<img class="el-width-25" src="{% static 'img/true.png' %}" />{% endif %}</td>
            <td>{% if project.url %}<a target="_blank" href="{{ project.url }}" class="blue-link">{{ project.url }}</a>{% endif %}{% if project.reason %}{{ project.reason }}{% endif %}</td>
            <td>{% if project.skill.all %}{% for skill in project.skill.all %}<a target="_blank" class="blue-link" href="{% url 'participantsapp:projects' %}?search={{ skill.name|urlencode }}">{{ skill.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}{% else %}No data{% endif %}</td>
            <td><a target="_blank" class="blue-link" href="{% url 'participantsapp:projects' %}?search={{ project.manager }}">{{ project.manager }}</td>
            <td>{{ project.date_start|date:"d M Y" }}</td>
            <td>{% if project.working_now %}in progress{% else %}{{ project.date_end|date:"d M Y" }}{% endif %}</td>
            <td><a target="_blank" class="blue-link" href="{% url 'participantsapp:projects' %}?search={{ project.developer.last_name }}+{{ project.developer.first_name }}">{{ project.developer.last_name }} {{ project.developer.first_name }}</a></td>
            {% if request.user.is_staff %}<td class="center">{% if project.nda %}<img class="el-width-25" src="{% static 'img/true.png' %}" />{% endif %}</td>{% endif %}
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <div class="clear">
        <p>No Projects found</p>
      </div>
    {% endif %}
    {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
          {% if page_obj.has_previous %}
            <a href="{% url 'participantsapp:projects' %}?page={{ page_obj.previous_page_number }}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}"><img class="el-width-25" src="{% static 'img/previous.png' %}"></a>
          {% endif %}
          <span class="page-current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
            <a href="{% url 'participantsapp:projects' %}?page={{ page_obj.next_page_number }}{% if request.GET.orderby %}&orderby={{ request.GET.orderby }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}"><img class="el-width-25" src="{% static 'img/next.png' %}"></a>
          {% endif %}
        </span>
      </div>
    {% endif %}
  </div>
</div>    
{% endblock %}

templates/quiz.html
{% extends "base.html" %}
{% load base_extra staticfiles %}
{% block title %}Quiz{% endblock %}
{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/chosen.min.css' %}" type="text/css" />
  <script type="text/javascript" src="{% static 'js/chosen.jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/skill_field_widget.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container mt-100">
  <div class="row">
    <div class="col-sm-6 col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong> Quiz </strong>
        </div>
        <div class="panel-body">
          <form action="{% url 'participantsapp:quiz' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
              <div class="row">
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                  {{ form.as_p }}
                  <input id="user_id" type="hidden" value="{% if not request.user.is_staff %}{{ request.user.id }}{% endif %}" />
                  <div class="form-group">
                    <a class="btn btn-info addproject btn-proj" href="{% url 'participantsapp:projects' %}">Projects</a>
                    <input type="submit" class="btn btn-lg btn-info btn-block btn-proj" value="Add project">
                  </div>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
    <div class="copyright"> LightIT © 2016 </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load base_extra %}
{% block title %}Registration{% endblock %}
{% block content %}
<div class="container mt-150">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <div class="panel panel-default">                    
        <div class="panel-heading">
          <strong>Registration</strong>
        </div>
        <div class="panel-body">
          <form action="{% url 'participantsapp:register' %}" method="POST">
            {% csrf_token %}
            <fieldset>
              <div class="row">
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                  {% for field in form %}
                    <div class="form-group">
                      <div class="input-group">
                        <span class="input-group-addon">
                          <i class="glyphicon glyphicon-{{ field.name|glyphicon_tags }}"></i>
                        </span>
                        {{ field }}
                      </div>
                      {% if field.errors %}
                        {{ field.errors }}
                      {% endif %}
                    </div>
                  {% endfor %}
                  <div class="form-group">
                    <input type="submit" class="btn btn-lg btn-info btn-block" value="Sign up">
                  </div>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright"> LightIT © 2016 </div>
</div>
{% endblock %}